### ISSUE TITLE
What if there is both route1 and route2? 

### ISSUE THREAD

**Issue by suustenvoorde** [NathanNeelis/web-app-from-scratch-2021#11]
https://github.com/NathanNeelis/web-app-from-scratch-2021/blob/f2446571bf9b41aa5aa6b2c3bfb8fc9386c8a781/js/modules/ui.js#L12

Maybe an extra if/else; what if they are both available?

**Comment by NathanNeelis** [comment]
At the moment, if both route 1 and route 2 are present, they get both loaded, because I used an if statement twice and not an if-else statement. But I agree, that's not how it's supposed to be. So I fixed it with an extra if/else statement
