### ISSUE TITLE
Peer Review 1

### ISSUE THREAD

**Issue by NinaPajonk** [NathanNeelis/web-app-from-scratch-2021#2]
**Repository:**

- Repo description:  Check, duidelijk doel van de app beschreven. Goed begonnen met het stellen van een vraag wat gelijk dus het probleem aangeeft.
- Open to issues: Check
- .gitignore: Check
- Concept: Kan nog uitgebreider beschreven worden, maar komt van de loop van het project van zelfwel.
- API description - Naam API "Ratelimits" mist nog beschrijving. Aan de naam af te lezen, kan ik me natuurlijk heel goed voorstellen wat de API voor informatie geeft. Maar een kleine beschrijving erbij zou fijn zijn. 
- License: Check, link doet het ook.

Vind trouwens in de repo de project status erg overzichtelijk en handig gedaan!

**Code:**

-  Comments: Check, code bevat netjes comments, waardoor ik het makkelijk kan volgen.
-  Resources: Check, ook bij de stukjes code vernoemt.
-  Website staat al live, leuk gedaan met hover, scale. 
- Ik vind dat je code er heel clean uit zien, en kan goed volgen wat je aan het doen hebt. Over de code zelf kan ik je weinig feedback geven omdat mijn kennis nog niet al te groot is op dit gebied.

**Comment by NathanNeelis** [comment]
Bedankt voor de feedback! 
• Ik heb de API description geupdate.
• Repo description ga ik updaten gaande het project, als het voor mezelf ook wat duidelijker wordt :)
