### ISSUE TITLE
Peer review 12-02-2021

### ISSUE THREAD

**Issue by Jelmerovereem** [NathanNeelis/web-app-from-scratch-2021#3]
_Following [peer review-2](https://github.com/cmda-minor-web/web-app-from-scratch-2021/blob/master/course/peer-review-2.md)_

### Repository
- [x] Live demo link 🌐 
- [x] Concept described in the readme ✍️ 
- [x] API described in readme 🙊 
- [x] Actor and interaction diagram included

### Code

- Using the Actor diagram, figure out the structure of the code 🏗️ 
   - [x] Do the actors make sense to you?
   - [x] Do you see any function you wouldn't expect for a certain actor?
- Using the interaction diagram, figure out how the app functions 🌊 
    - [x] Does the flow make sense to you?
    - [x] Does anything work differently than you would code it?
 - Live demo 🖱️ 
    - [x] Does it work the way you would expect it to?
       - [x] The search bar works as I expected. (But only searches on movies at the time)
       - [x] I yet can't click on the movies/series to get a detailed page.
    - [ ] What features or improvements would you like to see?
       - Maybe a short description for every result on the overview page  
 - Browse the code 👨‍💻 
    - [x] Has it already been structured according to the diagrams?
    - [x] Structural improvements: Structure is great! Very clean and understandable.
    - [x] [Best practices ](https://github.com/cmda-minor-web/best-practices/blob/master/javascript.md)
       - [x] Little bit waterfall code at getdata.js. Take a look at: [Best practices waterfall vs returning values](https://github.com/cmda-minor-web/best-practices/blob/master/javascript.md#waterfall--vs-returning-values-) 
    - [x] Consistency
    - [x] Naming conventions. Do the names make sense?
       - I understand the names and what they stand for 👍

**Comment by NathanNeelis** [comment]
Hi Jelmer,

De meeste punten heb ik aangepast.

Bedankt voor je feedback!
