### ISSUE TITLE
Code review week 2

### ISSUE THREAD

**Issue by RobinFrugte97** [NathanNeelis/web-app-from-scratch-2021#4]
Hey Nathan!

Goeie uitwerking! Search werkt lekker, ook met local storage zie ik? Nice!

Heb je al naar de diagrams gekeken? Kon ze niet terug vinden in je readme. Kijk goed of je diagrams exact overeenkomen met je code, je hebt je modules al goed duidelijk naamgegeven dus dat werkt in je voordeel. [Jordy](https://github.com/joordy/web-app-from-scratch-2021#-actor-diagram) heeft een heel redelijke uitwerking van zijn diagrams, kijk daar eens naar als je niet zeker bent.

Je codestructuur is erg goed! Erg netjes en overzichtelijk. Geen globalscope vervuiling ook.
Je fetcht vanuit je router, netjes! Goeie modules ook, je naamgeving is prettig simpel.

Je hebt een map en een filter, goed dat je je JSON data aanpast!

Kleine tip wat betreft het exporteren van functies: Als je in een module meerdere functies wilt exporteren, kan je onderaan 
`export { function1, function2 }` zetten, dan hoef je niet export voor elke functie te zetten. Hoe je het nu doet is ook prima hoor!

Klopt het dat #movies het alleen doet als je iets in je localstorage hebt staan? 

Detailpaginas moet je denk ik ook nog uitwerken, ze staan wel in je router geloof ik.

Je bent lekker op weg, kijk nog even goed naar de rubric en ga zo door!

**Comment by NathanNeelis** [comment]
Hi Robin!

- De actor en interaction diagram heb ik toegevoegd aan de readme.
- Bedankt voor je export tip, deze heb ik toegepast.
- De bug in #movies had iets te maken met hoe ik mijn HTML renderde, dit heb ik opgelost.
- Detailpagina is ook gemaakt

Nu nog bezig met de laatste updates aan me readme.

Bedankt voor je feedback!
