### ISSUE TITLE
First load is not giving back the data at route #movies

### ISSUE THREAD

**Issue by suustenvoorde** [NathanNeelis/web-app-from-scratch-2021#6]
<img width="1530" alt="Schermafbeelding 2021-02-14 om 10 20 06" src="https://user-images.githubusercontent.com/61702002/107872908-3788a900-6eae-11eb-975d-69b316fd280a.png">

**Comment by NathanNeelis** [comment]
Fixed this issue. 
I had a `section.innerHTML = "";` that was causing some problems. I had to rewrite a part of my rendering module to fix this.
