### ISSUE TITLE
To make it more readable, get every import on one line 

### ISSUE THREAD

**Issue by suustenvoorde** [NathanNeelis/web-app-from-scratch-2021#8]
https://github.com/NathanNeelis/web-app-from-scratch-2021/blob/f2446571bf9b41aa5aa6b2c3bfb8fc9386c8a781/js/modules/routes.js#L1-L17

For example check Jonah: https://github.com/theonejonahgold/web-app-from-scratch-2021/blob/master/scripts/modules/component.js

**Comment by NathanNeelis** [comment]
That is initially what I wrote, but my Beautify extensions thought differently. 
Fixed it, by telling my Beautify not to make it more beautiful.
