### ISSUE TITLE
Why do you call this function here?

### ISSUE THREAD

**Issue by suustenvoorde** [NathanNeelis/web-app-from-scratch-2021#9]
https://github.com/NathanNeelis/web-app-from-scratch-2021/blob/f2446571bf9b41aa5aa6b2c3bfb8fc9386c8a781/js/modules/routes.js#L29

Isn't this only necessary when the user is submitting the value in the search bar?

**Comment by NathanNeelis** [comment]
No, because it sets the stored value from the local storage as the value of the input field. But even so, it was unnecessary to call it there, so I removed it.
